name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-retention-days: 7
      build-android: true
      build-windows: true
      build-linux: false
      build-macos: false
      package-windows-setup: false
